// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-JjK-2Lbg6_6sN4z7hI-shB5rkqV5t0',
    appId: '1:602159356756:web:102efb53ea4b17188186c1',
    messagingSenderId: '602159356756',
    projectId: 'my-learning-dart',
    authDomain: 'my-learning-dart.firebaseapp.com',
    storageBucket: 'my-learning-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa4NAlknWChyoPgq0dNI0w-8XSTrIsN-I',
    appId: '1:602159356756:android:1bb5e2103e949c888186c1',
    messagingSenderId: '602159356756',
    projectId: 'my-learning-dart',
    storageBucket: 'my-learning-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBthncNQ5dM1AbB9O32cqMsFCC28UWoLWw',
    appId: '1:602159356756:ios:94a3800a69d491938186c1',
    messagingSenderId: '602159356756',
    projectId: 'my-learning-dart',
    storageBucket: 'my-learning-dart.appspot.com',
    iosClientId: '602159356756-2of2943htep1f2c5ra2elqheo1dsbdg1.apps.googleusercontent.com',
    iosBundleId: 'com.exam',
  );
}
